version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        ports:
            - 8000:8000
        volumes:
            - .:/go/src
        networks:
            - test
networks:
    test:
        external: true